In [84]:
import requests
import time
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from sklearn.metrics import accuracy_score, r2_score
from sklearn.model_selection import train_test_split
import ast
import os
import sys

from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from tensorflow.keras.regularizers import L2,L1,L1L2
from tensorflow.keras.layers import Dropout

In [85]:
sys.path.append(os.path.abspath('../Helper Functions'))
from objectives import *

In [168]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
data_file_path = os.path.join(parent_dir, 'LOL Data//')

In [87]:
# Read all csv files with games data from different rank divions
Chall = pd.read_csv(data_file_path + 'CHALLENGERS.csv',index_col=False)
GM = pd.read_csv(data_file_path +'GRANDMASTERS.csv',index_col=False)
GM_2 = pd.read_csv(data_file_path +'GM.csv',index_col=False)
Master = pd.read_csv(data_file_path +'MASTERS.csv',index_col=False)
Diamond = pd.read_csv(data_file_path +'Diamond_games.csv',index_col=False)
Diamond_2 = pd.read_csv(data_file_path +'Diamond_games_2.csv',index_col=False)
Emerald = pd.read_csv(data_file_path +'Emerald_games.csv',index_col=False)
Platinum = pd.read_csv(data_file_path +'Plat_games.csv',index_col=False)
Gold = pd.read_csv(data_file_path +'Gold_games.csv',index_col=False)
Silver = pd.read_csv(data_file_path +'Silver_games.csv',index_col=False)
Bronze = pd.read_csv(data_file_path +'Bronze_games.csv',index_col=False)
Iron = pd.read_csv(data_file_path +'Iron_games.csv',index_col=False)
Others = pd.read_csv(data_file_path +'OTHERS.csv',index_col=False)

In [88]:
# Reset index to be concatenated in the right way
Chall.reset_index(drop=True, inplace=True)
GM.reset_index(drop=True, inplace=True)
GM_2.reset_index(drop=True, inplace=True)
Master.reset_index(drop=True, inplace=True)
Diamond.reset_index(drop=True, inplace=True)
Diamond_2.reset_index(drop=True, inplace=True)
Emerald.reset_index(drop=True, inplace=True)
Platinum.reset_index(drop=True, inplace=True)
Gold.reset_index(drop=True, inplace=True)
Silver.reset_index(drop=True, inplace=True)
Bronze.reset_index(drop=True, inplace=True)
Iron.reset_index(drop=True, inplace=True)
Others.reset_index(drop=True, inplace=True)

In [89]:
all_data = pd.concat([Chall,GM,  GM_2,Master, Diamond, Diamond_2, Emerald, Platinum, Gold, Silver, Bronze, Iron, Others],axis=0)

In [7]:
matches_list = all_data["MATCH ID"].to_list()

In [8]:
file_path = "all_mmatches_id.txt"

# Open the file in write mode and save the list
with open(file_path, "w") as file:
    for number in matches_list:
        file.write(f"{number}\n")

In [90]:
all_data

,BLUE TOP,BLUE JUNGLE,BLUE MID,BLUE ADC,BLUE SUPPORT,RED TOP,RED JUNGLE,RED MID,RED ADC,RED SUPPORT,...,RED BOTTOM KDA,RED UTILITY KDA,RED FIRST BLOOD,BLUE FIRST BLOOD,RED FIRST TOWER,BLUE FIRST TOWER,TIME STAMP,BLUE WIN,MATCH ID,RANK
0,Sett,Poppy,Chogath,Caitlyn,Xerath,Darius,Diana,Yasuo,Ezreal,Yuumi,...,0.50,3.00,False,True,True,True,1603947,True,EUW1_7234969643,DIAMOND I EUW
1,Riven,Skarner,Chogath,Nilah,Lulu,Darius,Sejuani,Karma,Zeri,Soraka,...,1.20,2.00,False,True,False,True,984023,True,EUW1_7234956683,DIAMOND I EUW
2,KSante,LeeSin,Chogath,Xayah,Nami,Yone,Vi,Aurora,Draven,Seraphine,...,0.67,6.50,False,True,True,True,1288919,True,EUW1_7234935840,DIAMOND I EUW
3,Ambessa,Kayn,Azir,Caitlyn,Zoe,Zeri,Elise,Chogath,Lucian,Nami,...,1.00,1.55,False,True,True,True,1901947,True,EUW1_7234902774,DIAMOND I EUW
4,Riven,Amumu,Kassadin,Corki,Rell,Jayce,Shyvana,Viktor,Ezreal,Poppy,...,2.40,1.30,True,False,True,True,2152063,True,EUW1_7234038609,DIAMOND I EUW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79807,Renekton,Taliyah,Jayce,Swain,Seraphine,Gangplank,LeeSin,Yone,Jhin,Leblanc,...,1.20,2.57,True,False,True,True,1873478,True,KR_7364278794,OTHERS
79808,Kayle,XinZhao,Akali,Jhin,Garen,Zilean,LeeSin,Neeko,Lucian,Soraka,...,2.78,6.20,False,True,True,True,2360066,False,KR_7363219585,OTHERS
79809,Kayle,Skarner,Leblanc,Kaisa,Thresh,Ambessa,Rammus,Azir,Varus,Lux,...,2.33,2.60,False,True,True,False,1551729,False,KR_7363150700,OTHERS
79810,Sylas,Nocturne,Akali,Jhin,Leona,Jax,LeeSin,Leblanc,Ezreal,Seraphine,...,6.00,3.33,False,True,True,False,1922164,False,KR_7363063958,OTHERS
79811,Swain,Shyvana,Zac,Caitlyn,Leona,Chogath,Skarner,Yasuo,Ashe,Alistar,...,3.25,3.25,False,True,True,True,1540146,False,KR_7363000800,OTHERS

In [91]:
# Compute cs/min for each role (except for supports as they don't farm)
def compute_cs_min(all_data):
    all_data['BLUE TOP CS/MIN'] = round(all_data['BLUE TOP CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['BLUE JUNGLE CS/MIN'] = round(all_data['BLUE JUNGLE CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['BLUE MID CS/MIN'] = round(all_data['BLUE MID CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['BLUE ADC CS/MIN'] = round(all_data['BLUE ADC CS'] / (all_data['TIME STAMP']/60000),1)


    all_data['RED TOP CS/MIN'] = round(all_data['RED TOP CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['RED JUNGLE CS/MIN'] = round(all_data['RED JUNGLE CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['RED MID CS/MIN'] = round(all_data['RED MID CS'] / (all_data['TIME STAMP']/60000),1)
    all_data['RED ADC CS/MIN'] = round(all_data['RED ADC CS'] / (all_data['TIME STAMP']/60000),1)

    
    return all_data

In [92]:
all_data = compute_cs_min(all_data)

In [93]:
all_data.columns

Index(['BLUE TOP', 'BLUE JUNGLE', 'BLUE MID', 'BLUE ADC', 'BLUE SUPPORT',
       'RED TOP', 'RED JUNGLE', 'RED MID', 'RED ADC', 'RED SUPPORT',
       'BLUE TOP LEVEL', 'BLUE JUNGLE LEVEL', 'BLUE MID LEVEL',
       'BLUE ADC LEVEL', 'BLUE SUPPORT LEVEL', 'RED TOP LEVEL',
       'RED JUNGLE LEVEL', 'RED MID LEVEL', 'RED ADC LEVEL',
       'RED SUPPORT LEVEL', 'BLUE TOP CS', 'BLUE JUNGLE CS', 'BLUE MID CS',
       'BLUE ADC CS', 'RED TOP CS', 'RED JUNGLE CS', 'RED MID CS',
       'RED ADC CS', 'BLUE TOP Items', 'BLUE JUNGLE Items', 'BLUE MID Items',
       'BLUE ADC Items', 'BLUE SUPPORT Items', 'RED TOP Items',
       'RED JUNGLE Items', 'RED MID Items', 'RED ADC Items',
       'RED SUPPORT Items', 'RED Turrets', 'BLUE Turrets', 'RED TOP INHIB',
       'RED MID INHIB', 'RED_BOT_INHIB', 'BLUE TOP INHIB', 'BLUE MID INHIB',
       'BLUE_BOT_INHIB', 'RED FIRE DRAGON', 'RED AIR DRAGON',
       'RED EARTH DRAGON', 'RED WATER DRAGON', 'RED HEXTECH DRAGON',
       'RED CHEMTECH DRAGON', 'RED ELDER DRAGON', 'BLUE FIRE DRAGON',
       'BLUE AIR DRAGON', 'BLUE EARTH DRAGON', 'BLUE WATER DRAGON',
       'BLUE HEXTECH DRAGON', 'BLUE CHEMTECH DRAGON', 'BLUE ELDER DRAGON',
       'RED BARON', 'BLUE BARON', 'RED RIFT', 'BLUE RIFT', 'RED GRUBS',
       'BLUE GRUBS', 'BLUE TOP KDA', 'BLUE JUNGLE KDA', 'BLUE MIDDLE KDA',
       'BLUE BOTTOM KDA', 'BLUE UTILITY KDA', 'RED TOP KDA', 'RED JUNGLE KDA',
       'RED MIDDLE KDA', 'RED BOTTOM KDA', 'RED UTILITY KDA',
       'RED FIRST BLOOD', 'BLUE FIRST BLOOD', 'RED FIRST TOWER',
       'BLUE FIRST TOWER', 'TIME STAMP', 'BLUE WIN', 'MATCH ID', 'RANK',
       'BLUE TOP CS/MIN', 'BLUE JUNGLE CS/MIN', 'BLUE MID CS/MIN',
       'BLUE ADC CS/MIN', 'RED TOP CS/MIN', 'RED JUNGLE CS/MIN',
       'RED MID CS/MIN', 'RED ADC CS/MIN'],
      dtype='object')

In [94]:
# DROP CS as we comptedd CS/MIN
all_data.drop(['BLUE TOP CS','BLUE JUNGLE CS', 'BLUE MID CS','BLUE ADC CS',
               'RED TOP CS','RED JUNGLE CS','RED MID CS', 'RED ADC CS'], axis=1,inplace= True)
# DROP TIMESTAMP
all_data.drop('TIME STAMP', axis=1, inplace=True)
# DROP MATCH ID
all_data.drop('MATCH ID', axis=1, inplace=True)

In [95]:
# DROP ITEMS LISTS 
all_data.drop(['RED TOP Items', 'RED JUNGLE Items', 'RED MID Items', 'RED ADC Items','RED SUPPORT Items', 
               'BLUE TOP Items', 'BLUE JUNGLE Items', 'BLUE MID Items','BLUE ADC Items','BLUE SUPPORT Items'], axis=1, inplace=True)

In [96]:
# Assume turrets are destroyed except those in red_turrets list
all_data['RED TOP_LANE OUTER_TURRET'] = 0
all_data['RED TOP_LANE INNER_TURRET'] = 0
all_data['RED TOP_LANE BASE_TURRET'] = 0

all_data['RED MID_LANE OUTER_TURRET'] = 0
all_data['RED MID_LANE INNER_TURRET'] = 0
all_data['RED MID_LANE BASE_TURRET'] = 0

all_data['RED BOT_LANE OUTER_TURRET'] = 0
all_data['RED BOT_LANE INNER_TURRET'] = 0
all_data['RED BOT_LANE BASE_TURRET'] = 0

all_data['RED MID_LANE NEXUS_TURRET'] = 0

In [97]:
# Assume turrets are destroyed except those in blue_turrets list
all_data['BLUE TOP_LANE OUTER_TURRET'] = 0
all_data['BLUE TOP_LANE INNER_TURRET'] = 0
all_data['BLUE TOP_LANE BASE_TURRET'] = 0

all_data['BLUE MID_LANE OUTER_TURRET'] = 0
all_data['BLUE MID_LANE INNER_TURRET'] = 0
all_data['BLUE MID_LANE BASE_TURRET'] = 0

all_data['BLUE BOT_LANE OUTER_TURRET'] = 0
all_data['BLUE BOT_LANE INNER_TURRET'] = 0
all_data['BLUE BOT_LANE BASE_TURRET'] = 0

all_data['BLUE MID_LANE NEXUS_TURRET'] = 0

In [98]:
blue_turrets = [
    'BLUE TOP_LANE OUTER_TURRET', 'BLUE MID_LANE OUTER_TURRET', 'BLUE BOT_LANE OUTER_TURRET',
    'BLUE TOP_LANE INNER_TURRET', 'BLUE MID_LANE INNER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
    'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE BASE_TURRET', 'BLUE BOT_LANE BASE_TURRET',
    'BLUE MID_LANE NEXUS_TURRET', 'BLUE MID_LANE NEXUS_TURRET'
]

# Vectorized solution for counting turret occurences
for turret in blue_turrets:
    all_data[turret] = all_data['BLUE Turrets'].apply(lambda turrets: turrets.count(turret))

In [99]:
red_turrets = ['RED TOP_LANE OUTER_TURRET','RED MID_LANE OUTER_TURRET','RED BOT_LANE OUTER_TURRET',
                        'RED TOP_LANE INNER_TURRET' , 'RED MID_LANE INNER_TURRET', 'RED BOT_LANE INNER_TURRET',
                        'RED TOP_LANE BASE_TURRET', 'RED MID_LANE BASE_TURRET', 'RED BOT_LANE BASE_TURRET',
                        'RED MID_LANE NEXUS_TURRET' , 'RED MID_LANE NEXUS_TURRET']


# Vectorized solution for counting turret occurences
for turret in red_turrets:
    all_data[turret] = all_data['RED Turrets'].apply(lambda turrets: turrets.count(turret))

In [100]:
all_data.drop(['RED Turrets','BLUE Turrets'], axis=1, inplace=True) # Drop them as we already get evert turret in a separate column

In [19]:
all_data.to_csv('all_data.csv', index=False)

In [20]:
all_data

,BLUE TOP,BLUE JUNGLE,BLUE MID,BLUE ADC,BLUE SUPPORT,RED TOP,RED JUNGLE,RED MID,RED ADC,RED SUPPORT,...,BLUE TOP_LANE OUTER_TURRET,BLUE TOP_LANE INNER_TURRET,BLUE TOP_LANE BASE_TURRET,BLUE MID_LANE OUTER_TURRET,BLUE MID_LANE INNER_TURRET,BLUE MID_LANE BASE_TURRET,BLUE BOT_LANE OUTER_TURRET,BLUE BOT_LANE INNER_TURRET,BLUE BOT_LANE BASE_TURRET,BLUE MID_LANE NEXUS_TURRET
0,Sett,Poppy,Chogath,Caitlyn,Xerath,Darius,Diana,Yasuo,Ezreal,Yuumi,...,0,1,1,0,0,1,0,0,1,2
1,Riven,Skarner,Chogath,Nilah,Lulu,Darius,Sejuani,Karma,Zeri,Soraka,...,1,1,1,1,1,1,0,1,1,2
2,KSante,LeeSin,Chogath,Xayah,Nami,Yone,Vi,Aurora,Draven,Seraphine,...,1,1,1,0,1,1,0,1,1,2
3,Ambessa,Kayn,Azir,Caitlyn,Zoe,Zeri,Elise,Chogath,Lucian,Nami,...,0,1,1,0,1,1,0,0,1,2
4,Riven,Amumu,Kassadin,Corki,Rell,Jayce,Shyvana,Viktor,Ezreal,Poppy,...,0,1,1,0,1,1,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,DrMundo,Vi,Viktor,Draven,Lux,Gwen,Pantheon,Galio,Jinx,Janna,...,0,0,0,0,0,0,0,0,1,2
32,Olaf,Talon,Ahri,Ezreal,Soraka,Darius,Skarner,Sylas,Caitlyn,Bard,...,0,1,1,0,0,0,0,0,0,0
33,Ambessa,XinZhao,Sylas,Caitlyn,Rell,Teemo,Ekko,Talon,Tristana,Pyke,...,0,0,0,0,0,0,0,0,0,2
34,Gangplank,Kayn,Akali,Ashe,Bard,Irelia,Lillia,TwistedFate,Ezreal,Lulu,...,0,1,1,0,1,1,0,0,1,2
35,Gnar,Volibear,Corki,Hwei,Rell,Yasuo,Lillia,Yone,Jhin,Pyke,...,0,1,1,0,0,0,0,0,0,2

In [343]:
all_data_adjusted = all_data

In [344]:
all_data_adjusted.drop('RANK', axis=1, inplace=True)

KeyError: "['RANK'] not found in axis"

In [345]:
all_data_adjusted

,BLUE TOP,BLUE JUNGLE,BLUE MID,BLUE ADC,BLUE SUPPORT,RED TOP,RED JUNGLE,RED MID,RED ADC,RED SUPPORT,...,BLUE TOP_LANE OUTER_TURRET,BLUE TOP_LANE INNER_TURRET,BLUE TOP_LANE BASE_TURRET,BLUE MID_LANE OUTER_TURRET,BLUE MID_LANE INNER_TURRET,BLUE MID_LANE BASE_TURRET,BLUE BOT_LANE OUTER_TURRET,BLUE BOT_LANE INNER_TURRET,BLUE BOT_LANE BASE_TURRET,BLUE MID_LANE NEXUS_TURRET
0,Sett,Poppy,Chogath,Caitlyn,Xerath,Darius,Diana,Yasuo,Ezreal,Yuumi,...,0,1,1,0,0,1,0,0,1,2
1,Riven,Skarner,Chogath,Nilah,Lulu,Darius,Sejuani,Karma,Zeri,Soraka,...,1,1,1,1,1,1,0,1,1,2
2,KSante,LeeSin,Chogath,Xayah,Nami,Yone,Vi,Aurora,Draven,Seraphine,...,1,1,1,0,1,1,0,1,1,2
3,Ambessa,Kayn,Azir,Caitlyn,Zoe,Zeri,Elise,Chogath,Lucian,Nami,...,0,1,1,0,1,1,0,0,1,2
4,Riven,Amumu,Kassadin,Corki,Rell,Jayce,Shyvana,Viktor,Ezreal,Poppy,...,0,1,1,0,1,1,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79807,Renekton,Taliyah,Jayce,Swain,Seraphine,Gangplank,LeeSin,Yone,Jhin,Leblanc,...,0,1,1,1,1,1,0,1,1,2
79808,Kayle,XinZhao,Akali,Jhin,Garen,Zilean,LeeSin,Neeko,Lucian,Soraka,...,0,1,1,0,0,0,0,0,1,0
79809,Kayle,Skarner,Leblanc,Kaisa,Thresh,Ambessa,Rammus,Azir,Varus,Lux,...,0,0,1,0,0,0,0,1,1,0
79810,Sylas,Nocturne,Akali,Jhin,Leona,Jax,LeeSin,Leblanc,Ezreal,Seraphine,...,0,0,0,0,0,0,0,0,0,0
79811,Swain,Shyvana,Zac,Caitlyn,Leona,Chogath,Skarner,Yasuo,Ashe,Alistar,...,0,1,1,0,0,0,0,1,1,2

In [81]:
# BLUE team dragon soul
def blue_dragon_soul(row):
    if row['BLUE FIRE DRAGON'] == 2:
       return  'FIRE SOUL'
    elif row['BLUE AIR DRAGON'] == 2:
       return  'AIR SOUL'
    elif row['BLUE WATER DRAGON'] == 2:
       return  'WATER SOUL'
    elif row['BLUE CHEMTECH DRAGON'] == 2:
       return  'CHEMTECH SOUL'
    elif row['BLUE HEXTECH DRAGON'] == 2:
       return  'HEXTECH SOUL'
    elif row['BLUE EARTH DRAGON'] == 2:
       return  'EARTH SOUL'
    else:
       return 'NO SOUL'

In [82]:
# BLUE team dragon soul
def red_dragon_soul(row):
    if row['RED FIRE DRAGON'] == 2:
        return  'FIRE SOUL'
    elif row['RED AIR DRAGON'] == 2:
        return  'AIR SOUL'
    elif row['RED WATER DRAGON'] == 2:
        return  'WATER SOUL'
    elif row['RED CHEMTECH DRAGON'] == 2:
        return  'CHEMTECH SOUL'
    elif row['RED HEXTECH DRAGON'] == 2:
        return  'HEXTECH SOUL'
    elif row['RED EARTH DRAGON'] == 2:
        return  'EARTH SOUL'
    else:
        return 'NO SOUL'

In [83]:
all_data_adjusted['BLUE SOUL'] = all_data_adjusted.apply(blue_dragon_soul, axis=1)
all_data_adjusted['RED SOUL'] = all_data_adjusted.apply(red_dragon_soul, axis=1)

In [346]:
all_data_adjusted

,BLUE TOP,BLUE JUNGLE,BLUE MID,BLUE ADC,BLUE SUPPORT,RED TOP,RED JUNGLE,RED MID,RED ADC,RED SUPPORT,...,BLUE TOP_LANE OUTER_TURRET,BLUE TOP_LANE INNER_TURRET,BLUE TOP_LANE BASE_TURRET,BLUE MID_LANE OUTER_TURRET,BLUE MID_LANE INNER_TURRET,BLUE MID_LANE BASE_TURRET,BLUE BOT_LANE OUTER_TURRET,BLUE BOT_LANE INNER_TURRET,BLUE BOT_LANE BASE_TURRET,BLUE MID_LANE NEXUS_TURRET
0,Sett,Poppy,Chogath,Caitlyn,Xerath,Darius,Diana,Yasuo,Ezreal,Yuumi,...,0,1,1,0,0,1,0,0,1,2
1,Riven,Skarner,Chogath,Nilah,Lulu,Darius,Sejuani,Karma,Zeri,Soraka,...,1,1,1,1,1,1,0,1,1,2
2,KSante,LeeSin,Chogath,Xayah,Nami,Yone,Vi,Aurora,Draven,Seraphine,...,1,1,1,0,1,1,0,1,1,2
3,Ambessa,Kayn,Azir,Caitlyn,Zoe,Zeri,Elise,Chogath,Lucian,Nami,...,0,1,1,0,1,1,0,0,1,2
4,Riven,Amumu,Kassadin,Corki,Rell,Jayce,Shyvana,Viktor,Ezreal,Poppy,...,0,1,1,0,1,1,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79807,Renekton,Taliyah,Jayce,Swain,Seraphine,Gangplank,LeeSin,Yone,Jhin,Leblanc,...,0,1,1,1,1,1,0,1,1,2
79808,Kayle,XinZhao,Akali,Jhin,Garen,Zilean,LeeSin,Neeko,Lucian,Soraka,...,0,1,1,0,0,0,0,0,1,0
79809,Kayle,Skarner,Leblanc,Kaisa,Thresh,Ambessa,Rammus,Azir,Varus,Lux,...,0,0,1,0,0,0,0,1,1,0
79810,Sylas,Nocturne,Akali,Jhin,Leona,Jax,LeeSin,Leblanc,Ezreal,Seraphine,...,0,0,0,0,0,0,0,0,0,0
79811,Swain,Shyvana,Zac,Caitlyn,Leona,Chogath,Skarner,Yasuo,Ashe,Alistar,...,0,1,1,0,0,0,0,1,1,2

In [347]:
# Drop champion as we are considering in game events not the champions
no_champion_data = all_data_adjusted.drop(['BLUE TOP','BLUE JUNGLE','BLUE MID','BLUE ADC','BLUE SUPPORT','RED TOP','RED JUNGLE','RED MID','RED ADC','RED SUPPORT'], axis=1)
no_champion_data

,BLUE TOP LEVEL,BLUE JUNGLE LEVEL,BLUE MID LEVEL,BLUE ADC LEVEL,BLUE SUPPORT LEVEL,RED TOP LEVEL,RED JUNGLE LEVEL,RED MID LEVEL,RED ADC LEVEL,RED SUPPORT LEVEL,...,BLUE TOP_LANE OUTER_TURRET,BLUE TOP_LANE INNER_TURRET,BLUE TOP_LANE BASE_TURRET,BLUE MID_LANE OUTER_TURRET,BLUE MID_LANE INNER_TURRET,BLUE MID_LANE BASE_TURRET,BLUE BOT_LANE OUTER_TURRET,BLUE BOT_LANE INNER_TURRET,BLUE BOT_LANE BASE_TURRET,BLUE MID_LANE NEXUS_TURRET
0,15,15,16,15,13,15,14,15,12,12,...,0,1,1,0,0,1,0,0,1,2
1,12,10,11,11,10,9,9,10,9,8,...,1,1,1,1,1,1,0,1,1,2
2,14,11,14,13,10,13,11,13,11,10,...,1,1,1,0,1,1,0,1,1,2
3,17,17,17,16,14,17,14,16,14,14,...,0,1,1,0,1,1,0,0,1,2
4,18,18,18,17,15,15,16,17,18,14,...,0,1,1,0,1,1,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79807,17,16,18,15,14,17,14,16,14,14,...,0,1,1,1,1,1,0,1,1,2
79808,17,16,17,16,17,18,18,18,17,15,...,0,1,1,0,0,0,0,0,1,0
79809,13,12,13,13,12,16,14,15,13,12,...,0,0,1,0,0,0,0,1,1,0
79810,14,15,15,16,13,18,15,17,15,14,...,0,0,0,0,0,0,0,0,0,0
79811,13,12,13,13,11,15,15,14,14,12,...,0,1,1,0,0,0,0,1,1,2

In [348]:
no_champion_data.columns

Index(['BLUE TOP LEVEL', 'BLUE JUNGLE LEVEL', 'BLUE MID LEVEL',
       'BLUE ADC LEVEL', 'BLUE SUPPORT LEVEL', 'RED TOP LEVEL',
       'RED JUNGLE LEVEL', 'RED MID LEVEL', 'RED ADC LEVEL',
       'RED SUPPORT LEVEL', 'RED TOP INHIB', 'RED MID INHIB', 'RED_BOT_INHIB',
       'BLUE TOP INHIB', 'BLUE MID INHIB', 'BLUE_BOT_INHIB', 'RED FIRE DRAGON',
       'RED AIR DRAGON', 'RED EARTH DRAGON', 'RED WATER DRAGON',
       'RED HEXTECH DRAGON', 'RED CHEMTECH DRAGON', 'RED ELDER DRAGON',
       'BLUE FIRE DRAGON', 'BLUE AIR DRAGON', 'BLUE EARTH DRAGON',
       'BLUE WATER DRAGON', 'BLUE HEXTECH DRAGON', 'BLUE CHEMTECH DRAGON',
       'BLUE ELDER DRAGON', 'RED BARON', 'BLUE BARON', 'RED RIFT', 'BLUE RIFT',
       'RED GRUBS', 'BLUE GRUBS', 'BLUE TOP KDA', 'BLUE JUNGLE KDA',
       'BLUE MIDDLE KDA', 'BLUE BOTTOM KDA', 'BLUE UTILITY KDA', 'RED TOP KDA',
       'RED JUNGLE KDA', 'RED MIDDLE KDA', 'RED BOTTOM KDA', 'RED UTILITY KDA',
       'RED FIRST BLOOD', 'BLUE FIRST BLOOD', 'RED FIRST TOWER',
       'BLUE FIRST TOWER', 'BLUE WIN', 'BLUE TOP CS/MIN', 'BLUE JUNGLE CS/MIN',
       'BLUE MID CS/MIN', 'BLUE ADC CS/MIN', 'RED TOP CS/MIN',
       'RED JUNGLE CS/MIN', 'RED MID CS/MIN', 'RED ADC CS/MIN',
       'RED TOP_LANE OUTER_TURRET', 'RED TOP_LANE INNER_TURRET',
       'RED TOP_LANE BASE_TURRET', 'RED MID_LANE OUTER_TURRET',
       'RED MID_LANE INNER_TURRET', 'RED MID_LANE BASE_TURRET',
       'RED BOT_LANE OUTER_TURRET', 'RED BOT_LANE INNER_TURRET',
       'RED BOT_LANE BASE_TURRET', 'RED MID_LANE NEXUS_TURRET',
       'BLUE TOP_LANE OUTER_TURRET', 'BLUE TOP_LANE INNER_TURRET',
       'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE OUTER_TURRET',
       'BLUE MID_LANE INNER_TURRET', 'BLUE MID_LANE BASE_TURRET',
       'BLUE BOT_LANE OUTER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
       'BLUE BOT_LANE BASE_TURRET', 'BLUE MID_LANE NEXUS_TURRET'],
      dtype='object')

In [351]:
# Try to consider only objective and neglecting players stats
obj_data = no_champion_data[[ 'RED FIRE DRAGON',
       'RED AIR DRAGON', 'RED EARTH DRAGON', 'RED WATER DRAGON',
       'RED HEXTECH DRAGON', 'RED CHEMTECH DRAGON', 'RED ELDER DRAGON',
       'BLUE FIRE DRAGON', 'BLUE AIR DRAGON', 'BLUE EARTH DRAGON',
       'BLUE WATER DRAGON', 'BLUE HEXTECH DRAGON', 'BLUE CHEMTECH DRAGON',
       'BLUE ELDER DRAGON', 'RED BARON', 'BLUE BARON',
       'RED GRUBS', 'BLUE GRUBS','RED TOP_LANE OUTER_TURRET', 'RED TOP_LANE INNER_TURRET',
       'RED TOP_LANE BASE_TURRET', 'RED MID_LANE OUTER_TURRET',
       'RED MID_LANE INNER_TURRET', 'RED MID_LANE BASE_TURRET',
       'RED BOT_LANE OUTER_TURRET', 'RED BOT_LANE INNER_TURRET',
       'RED BOT_LANE BASE_TURRET',
       'BLUE TOP_LANE OUTER_TURRET', 'BLUE TOP_LANE INNER_TURRET',
       'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE OUTER_TURRET',
       'BLUE MID_LANE INNER_TURRET', 'BLUE MID_LANE BASE_TURRET',
       'BLUE BOT_LANE OUTER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
       'BLUE BOT_LANE BASE_TURRET','BLUE TOP KDA', 'BLUE JUNGLE KDA',
       'BLUE MIDDLE KDA', 'BLUE BOTTOM KDA', 'BLUE UTILITY KDA', 'RED TOP KDA',
       'RED JUNGLE KDA', 'RED MIDDLE KDA', 'RED BOTTOM KDA', 'RED UTILITY KDA',
       'RED TOP INHIB',
       'RED MID INHIB', 'RED_BOT_INHIB', 'BLUE TOP INHIB', 'BLUE MID INHIB', 'BLUE_BOT_INHIB']]

In [106]:
# These columns after training and seeing model weights they introduce noises
no_champion = no_champion_data.drop(['BLUE MID_LANE NEXUS_TURRET','RED MID_LANE NEXUS_TURRET', 'RED RIFT','BLUE RIFT', 'RED FIRST BLOOD','BLUE FIRST BLOOD','RED FIRST TOWER','BLUE FIRST TOWER'], axis=1)    # DROP MID NEXUS TURRET SINCE IT IS SO OBVIOUS

In [28]:
no_champion_adjsuted.drop(['RED TOP INHIB', 'RED MID INHIB', 'RED_BOT_INHIB',
       'BLUE TOP INHIB', 'BLUE MID INHIB', 'BLUE_BOT_INHIB',], axis=1, inplace=True)

In [352]:
obj_data.columns

Index(['RED FIRE DRAGON', 'RED AIR DRAGON', 'RED EARTH DRAGON',
       'RED WATER DRAGON', 'RED HEXTECH DRAGON', 'RED CHEMTECH DRAGON',
       'RED ELDER DRAGON', 'BLUE FIRE DRAGON', 'BLUE AIR DRAGON',
       'BLUE EARTH DRAGON', 'BLUE WATER DRAGON', 'BLUE HEXTECH DRAGON',
       'BLUE CHEMTECH DRAGON', 'BLUE ELDER DRAGON', 'RED BARON', 'BLUE BARON',
       'RED GRUBS', 'BLUE GRUBS', 'RED TOP_LANE OUTER_TURRET',
       'RED TOP_LANE INNER_TURRET', 'RED TOP_LANE BASE_TURRET',
       'RED MID_LANE OUTER_TURRET', 'RED MID_LANE INNER_TURRET',
       'RED MID_LANE BASE_TURRET', 'RED BOT_LANE OUTER_TURRET',
       'RED BOT_LANE INNER_TURRET', 'RED BOT_LANE BASE_TURRET',
       'BLUE TOP_LANE OUTER_TURRET', 'BLUE TOP_LANE INNER_TURRET',
       'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE OUTER_TURRET',
       'BLUE MID_LANE INNER_TURRET', 'BLUE MID_LANE BASE_TURRET',
       'BLUE BOT_LANE OUTER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
       'BLUE BOT_LANE BASE_TURRET', 'BLUE TOP KDA', 'BLUE JUNGLE KDA',
       'BLUE MIDDLE KDA', 'BLUE BOTTOM KDA', 'BLUE UTILITY KDA', 'RED TOP KDA',
       'RED JUNGLE KDA', 'RED MIDDLE KDA', 'RED BOTTOM KDA', 'RED UTILITY KDA',
       'RED TOP INHIB', 'RED MID INHIB', 'RED_BOT_INHIB', 'BLUE TOP INHIB',
       'BLUE MID INHIB', 'BLUE_BOT_INHIB'],
      dtype='object')

In [353]:
# encoded_features = no_champion_adjsuted
encoded_features = obj_data

In [220]:
encoded_features.drop('BLUE WIN', axis=1, inplace= True)    # Win is the label so we drop it from features

KeyError: "['BLUE WIN'] not found in axis"

In [354]:
encoded_features.columns

Index(['RED FIRE DRAGON', 'RED AIR DRAGON', 'RED EARTH DRAGON',
       'RED WATER DRAGON', 'RED HEXTECH DRAGON', 'RED CHEMTECH DRAGON',
       'RED ELDER DRAGON', 'BLUE FIRE DRAGON', 'BLUE AIR DRAGON',
       'BLUE EARTH DRAGON', 'BLUE WATER DRAGON', 'BLUE HEXTECH DRAGON',
       'BLUE CHEMTECH DRAGON', 'BLUE ELDER DRAGON', 'RED BARON', 'BLUE BARON',
       'RED GRUBS', 'BLUE GRUBS', 'RED TOP_LANE OUTER_TURRET',
       'RED TOP_LANE INNER_TURRET', 'RED TOP_LANE BASE_TURRET',
       'RED MID_LANE OUTER_TURRET', 'RED MID_LANE INNER_TURRET',
       'RED MID_LANE BASE_TURRET', 'RED BOT_LANE OUTER_TURRET',
       'RED BOT_LANE INNER_TURRET', 'RED BOT_LANE BASE_TURRET',
       'BLUE TOP_LANE OUTER_TURRET', 'BLUE TOP_LANE INNER_TURRET',
       'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE OUTER_TURRET',
       'BLUE MID_LANE INNER_TURRET', 'BLUE MID_LANE BASE_TURRET',
       'BLUE BOT_LANE OUTER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
       'BLUE BOT_LANE BASE_TURRET', 'BLUE TOP KDA', 'BLUE JUNGLE KDA',
       'BLUE MIDDLE KDA', 'BLUE BOTTOM KDA', 'BLUE UTILITY KDA', 'RED TOP KDA',
       'RED JUNGLE KDA', 'RED MIDDLE KDA', 'RED BOTTOM KDA', 'RED UTILITY KDA',
       'RED TOP INHIB', 'RED MID INHIB', 'RED_BOT_INHIB', 'BLUE TOP INHIB',
       'BLUE MID INHIB', 'BLUE_BOT_INHIB'],
      dtype='object')

In [355]:
# encoded_dummies = pd.get_dummies(encoded_features , columns=['RED SOUL', 'BLUE SOUL'])

In [363]:
features = encoded_features.astype(int)
labels = all_data_adjusted['BLUE WIN']

In [388]:
X_train, X_test, Y_train, Y_test = train_test_split(features,labels,test_size=0.3)  # Train data represent 90% of all data 
x_cv,x_test , y_cv,y_test = train_test_split(X_test, Y_test,test_size=0.5)      # Dev and Test represent 10% and 10%

In [390]:
from tensorflow.keras.regularizers import L2
model = Sequential([
    # Dense(32, activation='relu', kernel_regularizer=l2(4e-4), input_shape=(X_train.shape[1],)),
    # Dense(16, activation = 'relu' ,kernel_regularizer=l2(4e-4)),
    Dense(1, activation='sigmoid', kernel_regularizer=L2(2e-4))     # 96.8, 97.9, 97.9 
])

In [391]:
model.compile(
    optimizer = tf.keras.optimizers.Adam(0.0001),
    loss = tf.keras.losses.BinaryCrossentropy()
)

In [392]:
model.fit(X_train_s,Y_train,epochs=30,validation_data=(x_cv,y_cv))

Epoch 1/30
14436/14436 ━━━━━━━━━━━━━━━━━━━━ 9s 618us/step - loss: 0.3401 - val_loss: 0.0850
Epoch 2/30
14436/14436 ━━━━━━━━━━━━━━━━━━━━ 9s 626us/step - loss: 0.0838 - val_loss: 0.0810
Epoch 3/30
14436/14436 ━━━━━━━━━━━━━━━━━━━━ 9s 638us/step - loss: 0.0802 - val_loss: 0.0804
Epoch 4/30
14436/14436 ━━━━━━━━━━━━━━━━━━━━ 9s 640us/step - loss: 0.0797 - val_loss: 0.0803
Epoch 5/30
12071/14436 ━━━━━━━━━━━━━━━━━━━━ 1s 520us/step - loss: 0.0808

KeyboardInterrupt:

In [393]:
import numpy as np
import pandas as pd

# Suppose X_train is a DataFrame
original_feature_names = X_train.columns.tolist()

weights, biases = model.layers[0].get_weights()
weights = weights.flatten()

sorted_indices = np.argsort(weights)[::-1]

weights_df = pd.DataFrame({
    'Feature': np.array(original_feature_names)[sorted_indices],
    'Weight': weights[sorted_indices]
})

print(weights_df)
weights_df.to_csv('NN.csv', index=False)    # Observe the weights

                       Feature    Weight
0                 BLUE TOP KDA  0.731914
1    BLUE MID_LANE BASE_TURRET  0.692791
2              BLUE BOTTOM KDA  0.681316
3              BLUE MIDDLE KDA  0.658991
4              BLUE JUNGLE KDA  0.658818
5   BLUE MID_LANE OUTER_TURRET  0.455642
6               BLUE MID INHIB  0.413743
7             BLUE UTILITY KDA  0.406800
8   BLUE MID_LANE INNER_TURRET  0.401199
9   BLUE BOT_LANE OUTER_TURRET  0.304517
10  BLUE TOP_LANE OUTER_TURRET  0.220105
11                  BLUE BARON  0.212483
12   BLUE BOT_LANE BASE_TURRET  0.197314
13              BLUE TOP INHIB  0.191873
14              BLUE_BOT_INHIB  0.190436
15           BLUE ELDER DRAGON  0.182680
16             BLUE AIR DRAGON  0.125181
17            BLUE FIRE DRAGON  0.114545
18         BLUE HEXTECH DRAGON  0.108493
19           BLUE WATER DRAGON  0.107067
20           BLUE EARTH DRAGON  0.104719
21        BLUE CHEMTECH DRAGON  0.095717
22   BLUE TOP_LANE BASE_TURRET  0.090945
23  BLUE TOP_LANE INNER_TURRET  0.021387
24  BLUE BOT_LANE INNER_TURRET  0.018134
25   RED BOT_LANE INNER_TURRET  0.018001
26                  BLUE GRUBS  0.000792
27                   RED GRUBS -0.025063
28   RED TOP_LANE INNER_TURRET -0.039738
29         RED CHEMTECH DRAGON -0.067648
30            RED WATER DRAGON -0.099779
31            RED EARTH DRAGON -0.101142
32    RED TOP_LANE BASE_TURRET -0.106574
33             RED FIRE DRAGON -0.116315
34          RED HEXTECH DRAGON -0.123009
35              RED AIR DRAGON -0.133422
36    RED BOT_LANE BASE_TURRET -0.174185
37            RED ELDER DRAGON -0.198028
38               RED TOP INHIB -0.211764
39               RED_BOT_INHIB -0.215424
40                   RED BARON -0.225919
41   RED BOT_LANE OUTER_TURRET -0.247151
42   RED TOP_LANE OUTER_TURRET -0.247987
43   RED MID_LANE INNER_TURRET -0.377689
44             RED UTILITY KDA -0.398567
45               RED MID INHIB -0.452098
46   RED MID_LANE OUTER_TURRET -0.459966
47              RED JUNGLE KDA -0.633949
48    RED MID_LANE BASE_TURRET -0.673297
49              RED MIDDLE KDA -0.683145
50              RED BOTTOM KDA -0.698949
51                 RED TOP KDA -0.787483

In [394]:
print(X_train.shape[1])

52

In [395]:
train_col = features.columns

In [396]:
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
parent_dir = Path(parent_dir)  # Convert if it was originally a string
file = parent_dir / 'Statistics' /'train_col.txt'
with open(file, 'w') as filetowrite:
    for i in train_col:
        filetowrite.write(str(i) + '\n')

In [397]:
from pathlib import Path

# Ensure parent_dir is a Path object
parent_dir = Path(parent_dir)  # Convert if it was originally a string
model.save(parent_dir / 'Statistics' / 'Win_Prob ANN_model.keras')  # keras format

In [398]:
Y_train_pred = model.predict(X_train)
Y_train_pred = (Y_train_pred>0.5).astype(int)
Y_train_pred

14436/14436 ━━━━━━━━━━━━━━━━━━━━ 6s 423us/step

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [399]:
accuracy_score(Y_train,Y_train_pred)

0.9477364437747874

In [400]:
Y_cv_pred = model.predict(x_cv)
Y_cv_pred = (Y_cv_pred>0.5).astype(int)
Y_cv_pred

3094/3094 ━━━━━━━━━━━━━━━━━━━━ 1s 403us/step

array([[0],
       [1],
       [1],
       ...,
       [1],
       [0],
       [0]])

In [401]:
accuracy_score(y_cv,Y_cv_pred)

0.9679244329948982

In [402]:
Y_test_pred = model.predict(x_test)
Y_test_pred = (Y_test_pred>0.5).astype(int)
Y_test_pred

3094/3094 ━━━━━━━━━━━━━━━━━━━━ 1s 418us/step

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [1]])

In [403]:
accuracy_score(y_test,Y_test_pred)

0.9681668939738344

In [ ]:
'''
THE FOLLOWING IS A TEST FOR THE MODEL TO TRACK PERFORMANCE
'''

In [105]:
live_game_players = requests.get('https://127.0.0.1:2999/liveclientdata/playerlist',verify=False).json()
live_game_data =   requests.get('https://127.0.0.1:2999/liveclientdata/allgamedata',verify=False).json()
live_game_events = requests.get('https://127.0.0.1:2999/liveclientdata/eventdata',verify=False).json()  #67

C:\Users\mohsh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\mohsh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\mohsh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [106]:
game_df = pd.DataFrame()

In [107]:
game_dic = {}

In [108]:
game_dic['TIME STAMP'] = round(live_game_events['Events'][-1]['EventTime']/60,2)

In [109]:
game_dic

{'TIME STAMP': 0.0}

In [110]:
event_name_list = []

team_dic = {}
count1 = 9
count2 = 9

count3 = 4
count4 = 4

count5 = 9
count6 = 9
teams_count = 0
Blue_team = []
Red_team = []
for i in range(len(live_game_players)):
    items_list = [0]*6
    # championName = live_game_players[i]['championName']
    championLevel = live_game_players[i]['level']
    position = live_game_players[i]['position']
    kills = live_game_players[i]['scores']['kills']
    riot_id = live_game_players[i]['riotIdGameName']    # to get which player/team did the event
    assists = live_game_players[i]['scores']['assists']
    deaths = live_game_players[i]['scores']['deaths']
    team = 'BLUE' if live_game_players[i]['team'] == 'ORDER' else 'RED'
    cs = live_game_players[i]['scores']['creepScore']
    if team == 'BLUE':
        Blue_team.append(riot_id)
    else:
        Red_team.append(riot_id)
    kda = float(assists + kills) if deaths == 0 else round((assists+kills)/deaths,2)
    cs_per_min = 0 if game_dic['TIME STAMP'] == 0 else round(cs / game_dic['TIME STAMP'],1)
    # for j in range(len(live_game_players[i]['items'])):  # Loop over items neglecting slot 6 "ward slot"
    #     if live_game_players[i]['items'][j]['slot'] == 6:
    #         pass
    #     else:
    #         items_list[live_game_players[i]['items'][j]['slot']] += live_game_players[i]['items'][j]['itemID']

    if live_game_players[i]['position'] == 'TOP':
        # team_dic.update({f'{team} TOP' : championName})
        team_dic.update({f'{team} TOP KDA' : kda})
        team_dic.update({f'{team} TOP LEVEL' :championLevel})
        # team_dic.update({f'{team} TOP Items' : items_list})
        team_dic.update({f'{team} TOP CS/MIN' : cs_per_min})
    elif live_game_players[i]['position'] == 'JUNGLE' or live_game_players[i]['position'] == '':
        # team_dic.update({f'{team} JUNGLE' : championName})
        team_dic.update({f'{team} JUNGLE KDA' : kda})
        team_dic.update({f'{team} JUNGLE LEVEL' : championLevel})
        # team_dic.update({f'{team} JUNGLE Items' : items_list}) 
        team_dic.update({f'{team} JUNGLE CS/MIN' : cs_per_min})

    elif live_game_players[i]['position'] == 'MIDDLE':
        # team_dic.update({f'{team} MID' : championName})
        team_dic.update({f'{team} MIDDLE KDA' : kda})
        team_dic.update({f'{team} MID LEVEL' : championLevel})
        # team_dic.update({f'{team} MIDDLE Items' : items_list}) 
        team_dic.update({f'{team} MID CS/MIN' : cs_per_min})

    elif live_game_players[i]['position'] == 'BOTTOM':
        # team_dic.update({f'{team} ADC' : championName})
        team_dic.update({f'{team} ADC KDA' : kda})
        team_dic.update({f'{team} ADC LEVEL' : championLevel})
        # team_dic.update({f'{team} ADC Items' : items_list})  
        team_dic.update({f'{team} ADC CS/MIN' : cs_per_min})

    elif live_game_players[i]['position'] == 'UTILITY':
        # team_dic.update({f'{team} SUPPORT' :championName})
        team_dic.update({f'{team} UTILITY KDA' : kda})
        team_dic.update({f'{team} SUPPORT LEVEL' : championLevel})
        # team_dic.update({f'{team} SUPPORT Items' : items_list}) 
    
    # Neglicting ARAM games
    elif live_game_players[i]['position'] == 'Invalid':
        pass

    else:
        print('----------------- ERROR -----------------')


    

    count2 += 1
    count4 += 1
    count6 += 1





    if i%count1 == 0 and i!= 0:
        count1 = count2
        game_df = pd.concat([game_df,pd.DataFrame([team_dic])],ignore_index=True)

In [227]:
# UNZIP BLUE TEAM ITEMS
BLUE_TOP_adjusted_df = pd.DataFrame(game_df['BLUE TOP Items'].tolist(),
                           columns=['BLUE TOP Item0', 'BLUE TOP Item1', 'BLUE TOP Item2', 'BLUE TOP Item3', 'BLUE TOP Item4', 'BLUE TOP Item5'])

BLUE_JUNGLE_adjusted_df = pd.DataFrame(game_df['BLUE JUNGLE Items'].tolist(),
                           columns=['BLUE JUNGLE Item0', 'BLUE JUNGLE Item1', 'BLUE JUNGLE Item2', 'BLUE JUNGLE Item3', 'BLUE JUNGLE Item4', 'BLUE JUNGLE Item5'])

BLUE_MIDDLE_adjusted_df = pd.DataFrame(game_df['BLUE MIDDLE Items'].tolist(),
                           columns=['BLUE MIDDLE Item0', 'BLUE MIDDLE Item1', 'BLUE MIDDLE Item2', 'BLUE MIDDLE Item3', 'BLUE MIDDLE Item4', 'BLUE MIDDLE Item5'])

BLUE_ADC_adjusted_df = pd.DataFrame(game_df['BLUE ADC Items'].tolist(),
                           columns=['BLUE ADC Item0', 'BLUE ADC Item1', 'BLUE ADC Item2', 'BLUE ADC Item3', 'BLUE ADC Item4', 'BLUE ADC Item5'])

BLUE_SUPPORT_adjusted_df = pd.DataFrame(game_df['BLUE SUPPORT Items'].tolist(),
                           columns=['BLUE SUPPORT Item0', 'BLUE SUPPORT Item1', 'BLUE SUPPORT Item2', 'BLUE SUPPORT Item3', 'BLUE SUPPORT Item4', 'BLUE SUPPORT Item5'])

In [228]:
# UNZIP RED TEAM ITEMS
RED_TOP_adjusted_df = pd.DataFrame(game_df['RED TOP Items'].tolist(),
                           columns=['RED TOP Item0', 'RED TOP Item1', 'RED TOP Item2', 'RED TOP Item3', 'RED TOP Item4', 'RED TOP Item5'])

RED_JUNGLE_adjusted_df = pd.DataFrame(game_df['RED JUNGLE Items'].tolist(),
                           columns=['RED JUNGLE Item0', 'RED JUNGLE Item1', 'RED JUNGLE Item2', 'RED JUNGLE Item3', 'RED JUNGLE Item4', 'RED JUNGLE Item5'])

RED_MIDDLE_adjusted_df = pd.DataFrame(game_df['RED MIDDLE Items'].tolist(),
                           columns=['RED MIDDLE Item0', 'RED MIDDLE Item1', 'RED MIDDLE Item2', 'RED MIDDLE Item3', 'RED MIDDLE Item4', 'RED MIDDLE Item5'])

RED_ADC_adjusted_df = pd.DataFrame(game_df['RED ADC Items'].tolist(),
                           columns=['RED ADC Item0', 'RED ADC Item1', 'RED ADC Item2', 'RED ADC Item3', 'RED ADC Item4', 'RED ADC Item5'])

RED_SUPPORT_adjusted_df = pd.DataFrame(game_df['RED SUPPORT Items'].tolist(),
                            columns=['RED SUPPORT Item0', 'RED SUPPORT Item1', 'RED SUPPORT Item2', 'RED SUPPORT Item3', 'RED SUPPORT Item4', 'RED SUPPORT Item5'])

In [229]:
game_df.reset_index(drop=True, inplace=True)
BLUE_TOP_adjusted_df.reset_index(drop=True, inplace=True)
BLUE_JUNGLE_adjusted_df.reset_index(drop=True, inplace=True)
BLUE_MIDDLE_adjusted_df.reset_index(drop=True, inplace=True)
BLUE_ADC_adjusted_df.reset_index(drop=True, inplace=True)
BLUE_SUPPORT_adjusted_df.reset_index(drop=True, inplace=True)
RED_TOP_adjusted_df.reset_index(drop=True, inplace=True)
RED_JUNGLE_adjusted_df.reset_index(drop=True, inplace=True)
RED_MIDDLE_adjusted_df.reset_index(drop=True, inplace=True)
RED_ADC_adjusted_df.reset_index(drop=True, inplace=True)
RED_SUPPORT_adjusted_df.reset_index(drop=True, inplace=True)

In [230]:
adjusted_items_games = pd.concat([game_df,BLUE_TOP_adjusted_df,BLUE_JUNGLE_adjusted_df,BLUE_MIDDLE_adjusted_df,BLUE_ADC_adjusted_df,BLUE_SUPPORT_adjusted_df,
                                 RED_TOP_adjusted_df,RED_JUNGLE_adjusted_df,RED_MIDDLE_adjusted_df,RED_ADC_adjusted_df,RED_SUPPORT_adjusted_df],axis=1)

In [111]:
adjusted_items_games = game_df

In [112]:
adjusted_items_games.drop('BLUE TOP Items',axis=1,inplace=True)
adjusted_items_games.drop('BLUE JUNGLE Items',axis=1,inplace=True)
adjusted_items_games.drop('BLUE ADC Items',axis=1,inplace=True)
adjusted_items_games.drop('BLUE MIDDLE Items',axis=1,inplace=True)
adjusted_items_games.drop('BLUE SUPPORT Items',axis=1,inplace=True)

adjusted_items_games.drop('RED TOP Items',axis=1,inplace=True)
adjusted_items_games.drop('RED JUNGLE Items',axis=1,inplace=True)
adjusted_items_games.drop('RED MIDDLE Items',axis=1,inplace=True)
adjusted_items_games.drop('RED ADC Items',axis=1,inplace=True)
adjusted_items_games.drop('RED SUPPORT Items',axis=1,inplace=True)

KeyError: "['BLUE TOP Items'] not found in axis"

In [113]:
def live_game_init():
    red_towers = ['RED TOP_LANE OUTER_TURRET','RED MID_LANE OUTER_TURRET','RED BOT_LANE OUTER_TURRET',
                    'RED TOP_LANE INNER_TURRET' , 'RED MID_LANE INNER_TURRET', 'RED BOT_LANE INNER_TURRET',
                    'RED TOP_LANE BASE_TURRET', 'RED MID_LANE BASE_TURRET', 'RED BOT_LANE BASE_TURRET',
                    'RED MID_LANE NEXUS_TURRET' , 'RED MID_LANE NEXUS_TURRET']

    blue_towers =  ['BLUE TOP_LANE OUTER_TURRET','BLUE MID_LANE OUTER_TURRET','BLUE BOT_LANE OUTER_TURRET',
                    'BLUE TOP_LANE INNER_TURRET' , 'BLUE MID_LANE INNER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
                    'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE BASE_TURRET', 'BLUE BOT_LANE BASE_TURRET',
                    'BLUE MID_LANE NEXUS_TURRET' , 'BLUE MID_LANE NEXUS_TURRET']


    red_first_tower = False
    blue_first_tower = False

    red_top_inhib = 0
    red_mid_inhib = 0
    red_bot_inhib = 0


    blue_top_inhib = 0
    blue_mid_inhib = 0
    blue_bot_inhib = 0


    red_fire_dragons = 0
    red_water_dragons = 0
    red_earth_dragons = 0
    red_air_dragons = 0
    red_hextech_dragons = 0
    red_chemtech_dragons = 0
    red_elder_dragons = 0


    blue_fire_dragons = 0
    blue_water_dragons = 0
    blue_earth_dragons = 0
    blue_air_dragons = 0
    blue_hextech_dragons = 0
    blue_chemtech_dragons = 0
    blue_elder_dragons = 0


    red_barons = 0

    blue_barons = 0


    red_rift = False
    blue_rift = False

    red_hordes = 0

    blue_hordes = 0


    red_top_kda = 0.
    red_jungle_kda = 0.
    red_mid_kda = 0.
    red_adc_kda = 0.
    red_sup_kda = 0.
    red_first_blood = False

    blue_top_kda = 0.
    blue_jungle_kda = 0.
    blue_mid_kda = 0.
    blue_adc_kda = 0.
    blue_sup_kda = 0.
    blue_first_blood = False

    return red_towers, blue_towers ,red_top_inhib , red_mid_inhib ,red_bot_inhib, blue_top_inhib, blue_mid_inhib ,blue_bot_inhib,red_fire_dragons,red_water_dragons,red_earth_dragons,red_air_dragons,red_hextech_dragons,red_chemtech_dragons,red_elder_dragons,blue_fire_dragons,blue_water_dragons,blue_earth_dragons,blue_air_dragons,blue_hextech_dragons,blue_chemtech_dragons,blue_elder_dragons,red_barons,blue_barons,red_rift,blue_rift,red_hordes,blue_hordes, kills, deaths, assists, kda, red_first_tower, red_first_blood, blue_first_tower, blue_first_blood

In [114]:
red_turrets, blue_turrets ,red_top_inhib , red_mid_inhib ,red_bot_inhib, blue_top_inhib, blue_mid_inhib ,blue_bot_inhib,red_fire_dragons,red_water_dragons,red_earth_dragons,red_air_dragons,red_hextech_dragons,red_chemtech_dragons,red_elder_dragons,blue_fire_dragons,blue_water_dragons,blue_earth_dragons,blue_air_dragons,blue_hextech_dragons,blue_chemtech_dragons,blue_elder_dragons,red_barons,blue_barons,red_rift,blue_rift,red_hordes,blue_hordes, kills, deaths, assists, kda, red_first_tower, red_first_blood, blue_first_tower, blue_first_blood = live_game_init()

In [115]:
def mapping_turrets(turret):
    # Check for top turrets
    if turret == 'Turret_T2_L_03_A':
        return 'TOP_LANE OUTER_TURRET'
    elif turret == 'Turret_T2_L_02_A':
        return 'TOP_LANE INNER_TURRET'
    elif turret == 'Turret_T2_L_01_A':
        return 'TOP_LANE BASE_TURRET'
    
    # Check for mid turrets
    elif turret == 'Turret_T2_C_05_A':
        return 'MID_LANE OUTER_TURRET'
    elif turret == 'Turret_T2_C_04_A':
        return 'MID_LANE INNER_TURRET'
    elif turret == 'Turret_T2_C_03_A':
        return 'MID_LANE BASE_TURRET'
    elif turret == 'Turret_T2_C_02_A' or turret == 'Turret_T2_C_01_A':
        return 'MID_LANE NEXUS_TURRET'
    
    # Check for bot turrets
    elif turret == 'Turret_T2_R_03_A':
        return 'BOT_LANE OUTER_TURRET'
    elif turret == 'Turret_T2_R_02_A':
        return 'BOT_LANE INNER_TURRET'
    elif turret == 'Turret_T2_R_01_A':
        return 'BOT_LANE BASE_TURRET'

In [116]:
def mapping_inhibs(inhib):
    if inhib == 'Barracks_T2_L1':
        return 'TOP'
    elif inhib == 'Barracks_T2_C1':
        return 'MID'
    elif inhib == 'Barracks_T2_R1':
        return 'BOT'

In [117]:
# Consider team minions
Blue_team.append("Minion_T100")
Red_team.append('Minion_T200')

In [118]:
Blue_team

['Evistex', 'Lulu', 'Tristana', 'Mordekaiser', 'Smolder', 'Minion_T100']

In [119]:
Red_team

['Lucian', 'Fizz', 'Darius', 'Seraphine', 'Vi', 'Minion_T200']

In [120]:
event_dic = {}

for j in range(len(live_game_events['Events'])):
    event = live_game_events['Events'][j]
    event_name = event['EventName']
    event_time = event['EventTime']
    
    try:
        if event_name == 'FirstBlood':
            bplayer = any(s in event['Recipient'] for s in Blue_team)
            rplayer = any(s in event['Recipient'] for s in Red_team)
            if bplayer:
                blue_first_blood = True
            elif rplayer:
                red_first_blood = True
            else:
                print("ERROR IN FIRSTBLOOD")
        else:
            bplayer = any(s in event['KillerName'] for s in Blue_team)
            rplayer = any(s in event['KillerName'] for s in Red_team)

    except:
        print(event_name,event_time)
        print('Event with no KillerName')
        continue

    if bplayer:
        flag = 1
    elif rplayer:
        flag = 2
    else:
        flag = 3
        continue


    # First two events are standard: GameStart and MinionSpawning, so we nyeglect i == 0 and i == 1
    if j == 0 or j == 1:
        pass
    else:
        if flag == 1:
            if event_name == 'BaronKill':
                blue_barons += 1
            elif event_name == 'DragonKill':
                dragon_type = event['DragonType']
                blue_air_dragons, blue_fire_dragons, blue_earth_dragons, blue_water_dragons, blue_hextech_dragons, blue_chemtech_dragons, blue_elder_dragons = check_dragon_type(blue_air_dragons, blue_fire_dragons, blue_earth_dragons, blue_water_dragons, blue_hextech_dragons, blue_chemtech_dragons,blue_elder_dragons,dragon_type)
            elif event_name == 'TurretKilled':
                turret_name = "RED" + " " + mapping_turrets(event['TurretKilled'])
                red_turrets.remove(turret_name)
            elif event_name == 'FirstBrick':
                blue_first_tower = True
            elif event_name == 'InhibKilled':
                inhib_lane = mapping_inhibs(event['InhibKilled'])
                    # Counted for red team that destroyed the inhib
                if inhib_lane == 'TOP':
                    red_top_inhib += 1 
                elif inhib_lane == 'MID':
                    red_mid_inhib += 1
                elif inhib_lane == 'BOT':
                    red_bot_inhib += 1
            elif event_name == 'HordeKill':
                blue_hordes += 1
            elif event_name == 'HeraldKill':
                blue_rift = True
            # elif event_name == 'FirstBlood':
            #     blue_first_blood = True
        elif flag == 2:
            if event_name == 'BaronKill':
                red_barons += 1
            elif event_name == 'DragonKill':
                dragon_type = event['DragonType']
                red_air_dragons, red_fire_dragons, red_earth_dragons, red_water_dragons, red_hextech_dragons, red_chemtech_dragons, red_elder_dragons = check_dragon_type(red_air_dragons, red_fire_dragons, red_earth_dragons, red_water_dragons, red_hextech_dragons, red_chemtech_dragons, red_elder_dragons,dragon_type)
            elif event_name == 'TurretKilled':
                turret_name = 'BLUE' + ' ' + mapping_turrets(event['TurretKilled'])
                blue_turrets.remove(turret_name)
            elif event_name == 'FirstBrick':
                red_first_tower = True
            elif event_name == 'InhibKilled':
                inhib_lane = mapping_inhibs(event['InhibKilled'])
                # Counted for blue team that destroyed the inhib
                if inhib_lane == 'TOP':
                    blue_top_inhib += 1 
                elif inhib_lane == 'MID':
                    blue_mid_inhib += 1
                elif inhib_lane == 'BOT':
                    blue_bot_inhib += 1
            elif event_name == 'HordeKill':
                red_hordes += 1
            elif event_name == 'HeraldKill':
                red_rift = True
            # elif event_name == 'FirstBlood':
            #     red_first_blood = True
        else:
            print("------ Error Event -------")
        
    
event_dic.update({
    f'RED Barons': red_barons,

    'RED AIR Dragons': red_air_dragons,
    'RED FIRE Dragons': red_air_dragons,
    'RED EARTH Dragons': red_air_dragons,
    'RED WATER Dragons': red_air_dragons,
    'RED HEXTECH Dragons': red_air_dragons,
    'RED CHEMTECCH Dragons': red_air_dragons,
    'RED ELDER Dragons': red_air_dragons,

    f'RED RiftHerald': red_rift,
    f'RED Voidgrubs': red_hordes,

    'RED Turrets': red_turrets,
    'RED FIRST TOWER': red_first_tower,
    'RED TOP INHIB': red_top_inhib,
    'RED MID INHIB' : red_mid_inhib,
    'RED_BOT_INHIB' : red_bot_inhib,

    
    f'BLUE Barons': blue_barons,

    'BLUE AIR Dragons': blue_air_dragons,
    'BLUE FIRE Dragons': blue_air_dragons,
    'BLUE EARTH Dragons': blue_air_dragons,
    'BLUE WATER Dragons': blue_air_dragons,
    'BLUE HEXTECH Dragons': blue_air_dragons,
    'BLUE CHEMTECCH Dragons': blue_air_dragons,
    'BLUE ELDER Dragons': blue_air_dragons,

    f'BLUE RiftHerald': blue_rift,
    f'BLUE Voidgrubs': blue_hordes,

    f'BLUE Turrets': blue_turrets,
    'BLUE FIRST TOWER': blue_first_tower,
    'BLUE TOP INHIB': blue_top_inhib,
    'BLUE MID INHIB' : blue_mid_inhib,
    'BLUE_BOT_INHIB' : blue_bot_inhib,

    'BLUE FIRST BLOOD': blue_first_blood,
    'RED FIRST BLOOD': red_first_blood

})

GameStart 0.11448259651660919
Event with no KillerName

In [121]:
event_df = pd.DataFrame([event_dic])

In [122]:
event_df['RED TOP_LANE OUTER_TURRET'] = 0
event_df['RED TOP_LANE INNER_TURRET'] = 0
event_df['RED TOP_LANE BASE_TURRET'] = 0

event_df['RED MID_LANE OUTER_TURRET'] = 0
event_df['RED MID_LANE INNER_TURRET'] = 0
event_df['RED MID_LANE BASE_TURRET'] = 0

event_df['RED BOT_LANE OUTER_TURRET'] = 0
event_df['RED BOT_LANE INNER_TURRET'] = 0
event_df['RED BOT_LANE BASE_TURRET'] = 0

event_df['RED MID_LANE NEXUS_TURRET'] = 0

In [123]:
red_turrets = ['RED TOP_LANE OUTER_TURRET','RED MID_LANE OUTER_TURRET','RED BOT_LANE OUTER_TURRET',
                        'RED TOP_LANE INNER_TURRET' , 'RED MID_LANE INNER_TURRET', 'RED BOT_LANE INNER_TURRET',
                        'RED TOP_LANE BASE_TURRET', 'RED MID_LANE BASE_TURRET', 'RED BOT_LANE BASE_TURRET',
                        'RED MID_LANE NEXUS_TURRET' , 'RED MID_LANE NEXUS_TURRET']


# Iterate through each row and with correspoding index
for index, row in event_df.iterrows():
    # Set 1 for columns in the list, 0 otherwise
    for col in red_turrets:
        event_df.at[index, col] += 1 if col in row['RED Turrets'] else 0

In [124]:
event_df['BLUE TOP_LANE OUTER_TURRET'] = 0
event_df['BLUE TOP_LANE INNER_TURRET'] = 0
event_df['BLUE TOP_LANE BASE_TURRET'] = 0

event_df['BLUE MID_LANE OUTER_TURRET'] = 0
event_df['BLUE MID_LANE INNER_TURRET'] = 0
event_df['BLUE MID_LANE BASE_TURRET'] = 0

event_df['BLUE BOT_LANE OUTER_TURRET'] = 0
event_df['BLUE BOT_LANE INNER_TURRET'] = 0
event_df['BLUE BOT_LANE BASE_TURRET'] = 0

event_df['BLUE MID_LANE NEXUS_TURRET'] = 0

In [125]:
blue_turrets = ['BLUE TOP_LANE OUTER_TURRET','BLUE MID_LANE OUTER_TURRET','BLUE BOT_LANE OUTER_TURRET',
                        'BLUE TOP_LANE INNER_TURRET' , 'BLUE MID_LANE INNER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
                        'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE BASE_TURRET', 'BLUE BOT_LANE BASE_TURRET',
                        'BLUE MID_LANE NEXUS_TURRET' , 'BLUE MID_LANE NEXUS_TURRET']

# Iterate through each row and with correspoding index
for index, row in event_df.iterrows():
    # Set 1 for columns in the list, 0 otherwise
    for col in blue_turrets:
        event_df.at[index, col] += 1 if col in row['BLUE Turrets'] else 0

In [126]:
live_game_data = pd.concat([game_df, event_df], axis=1)

In [260]:
live_game_data.to_csv('tets.csv', index=False)

In [261]:
live_game_data['BLUE TOP Items'].tolist()

[[3040, 6657, 2055, 1011, 0, 0]]

In [262]:
# UNZIP BLUE TEAM ITEMS
BLUE_TOP_adjusted_df = pd.DataFrame(live_game_data['BLUE TOP Items'].tolist(),
                           columns=['BLUE TOP Item0', 'BLUE TOP Item1', 'BLUE TOP Item2', 'BLUE TOP Item3', 'BLUE TOP Item4', 'BLUE TOP Item5'])

BLUE_JUNGLE_adjusted_df = pd.DataFrame(live_game_data['BLUE JUNGLE Items'].tolist(),
                           columns=['BLUE JUNGLE Item0', 'BLUE JUNGLE Item1', 'BLUE JUNGLE Item2', 'BLUE JUNGLE Item3', 'BLUE JUNGLE Item4', 'BLUE JUNGLE Item5'])

BLUE_MIDDLE_adjusted_df = pd.DataFrame(live_game_data['BLUE MIDDLE Items'].tolist(),
                           columns=['BLUE MIDDLE Item0', 'BLUE MIDDLE Item1', 'BLUE MIDDLE Item2', 'BLUE MIDDLE Item3', 'BLUE MIDDLE Item4', 'BLUE MIDDLE Item5'])

BLUE_ADC_adjusted_df = pd.DataFrame(live_game_data['BLUE ADC Items'].tolist(),
                           columns=['BLUE ADC Item0', 'BLUE ADC Item1', 'BLUE ADC Item2', 'BLUE ADC Item3', 'BLUE ADC Item4', 'BLUE ADC Item5'])

BLUE_SUPPORT_adjusted_df = pd.DataFrame(live_game_data['BLUE SUPPORT Items'].tolist(),
                           columns=['BLUE SUPPORT Item0', 'BLUE SUPPORT Item1', 'BLUE SUPPORT Item2', 'BLUE SUPPORT Item3', 'BLUE SUPPORT Item4', 'BLUE SUPPORT Item5'])

In [263]:
# UNZIP RED TEAM ITEMS
RED_TOP_adjusted_df = pd.DataFrame(live_game_data['RED TOP Items'].tolist(),
                           columns=['RED TOP Item0', 'RED TOP Item1', 'RED TOP Item2', 'RED TOP Item3', 'RED TOP Item4', 'RED TOP Item5'])

RED_JUNGLE_adjusted_df = pd.DataFrame(live_game_data['RED JUNGLE Items'].tolist(),
                           columns=['RED JUNGLE Item0', 'RED JUNGLE Item1', 'RED JUNGLE Item2', 'RED JUNGLE Item3', 'RED JUNGLE Item4', 'RED JUNGLE Item5'])

RED_MIDDLE_adjusted_df = pd.DataFrame(live_game_data['RED MIDDLE Items'].tolist(),
                           columns=['RED MIDDLE Item0', 'RED MIDDLE Item1', 'RED MIDDLE Item2', 'RED MIDDLE Item3', 'RED MIDDLE Item4', 'RED MIDDLE Item5'])

RED_ADC_adjusted_df = pd.DataFrame(live_game_data['RED ADC Items'].tolist(),
                           columns=['RED ADC Item0', 'RED ADC Item1', 'RED ADC Item2', 'RED ADC Item3', 'RED ADC Item4', 'RED ADC Item5'])

RED_SUPPORT_adjusted_df = pd.DataFrame(live_game_data['RED SUPPORT Items'].tolist(),
                            columns=['RED SUPPORT Item0', 'RED SUPPORT Item1', 'RED SUPPORT Item2', 'RED SUPPORT Item3', 'RED SUPPORT Item4', 'RED SUPPORT Item5'])

In [264]:
# DROP ITEMS LISTS 
live_game_data.drop(['RED TOP Items', 'RED JUNGLE Items', 'RED MIDDLE Items', 'RED ADC Items','RED SUPPORT Items', 
               'BLUE TOP Items', 'BLUE JUNGLE Items', 'BLUE MIDDLE Items','BLUE ADC Items','BLUE SUPPORT Items'], axis=1, inplace=True)

In [265]:
# CONCAT THE UNPACKED ITMES TO THE DATAFRAME
live_game_adjusted = pd.concat([live_game_data,
                              BLUE_TOP_adjusted_df, BLUE_JUNGLE_adjusted_df, BLUE_MIDDLE_adjusted_df, BLUE_ADC_adjusted_df, BLUE_SUPPORT_adjusted_df,
                              RED_TOP_adjusted_df, RED_JUNGLE_adjusted_df, RED_MIDDLE_adjusted_df, RED_ADC_adjusted_df, RED_SUPPORT_adjusted_df], axis=1)

In [129]:
live_game_adjusted = live_game_data

In [130]:
live_game_adjusted.drop(['RED Turrets', 'BLUE Turrets'], axis=1, inplace=True)

In [131]:
live_game_adjusted.to_csv('live_game_data.csv', index=False)

In [268]:
one_hot_cols =  ['BLUE TOP',
 'BLUE JUNGLE',
 'BLUE MID',
 'BLUE ADC',
 'BLUE SUPPORT',
 'RED TOP',
 'RED JUNGLE',
 'RED MID',
 'RED ADC',
 'RED SUPPORT',
 'BLUE TOP Item0',
 'BLUE TOP Item1',
 'BLUE TOP Item2',
 'BLUE TOP Item3',
 'BLUE TOP Item4',
 'BLUE TOP Item5',
 'BLUE JUNGLE Item0',
 'BLUE JUNGLE Item1',
 'BLUE JUNGLE Item2',
 'BLUE JUNGLE Item3',
 'BLUE JUNGLE Item4',
 'BLUE JUNGLE Item5',
 'BLUE MIDDLE Item0',
 'BLUE MIDDLE Item1',
 'BLUE MIDDLE Item2',
 'BLUE MIDDLE Item3',
 'BLUE MIDDLE Item4',
 'BLUE MIDDLE Item5',
 'BLUE ADC Item0',
 'BLUE ADC Item1',
 'BLUE ADC Item2',
 'BLUE ADC Item3',
 'BLUE ADC Item4',
 'BLUE ADC Item5',
 'BLUE SUPPORT Item0',
 'BLUE SUPPORT Item1',
 'BLUE SUPPORT Item2',
 'BLUE SUPPORT Item3',
 'BLUE SUPPORT Item4',
 'BLUE SUPPORT Item5',
 'RED TOP Item0',
 'RED TOP Item1',
 'RED TOP Item2',
 'RED TOP Item3',
 'RED TOP Item4',
 'RED TOP Item5',
 'RED JUNGLE Item0',
 'RED JUNGLE Item1',
 'RED JUNGLE Item2',
 'RED JUNGLE Item3',
 'RED JUNGLE Item4',
 'RED JUNGLE Item5',
 'RED MIDDLE Item0',
 'RED MIDDLE Item1',
 'RED MIDDLE Item2',
 'RED MIDDLE Item3',
 'RED MIDDLE Item4',
 'RED MIDDLE Item5',
 'RED ADC Item0',
 'RED ADC Item1',
 'RED ADC Item2',
 'RED ADC Item3',
 'RED ADC Item4',
 'RED ADC Item5',
 'RED SUPPORT Item0',
 'RED SUPPORT Item1',
 'RED SUPPORT Item2',
 'RED SUPPORT Item3',
 'RED SUPPORT Item4',
 'RED SUPPORT Item5']

In [269]:
encoded_features = pd.get_dummies(live_game_adjusted, columns= one_hot_cols)

In [137]:
test_encoded_features = live_game_adjusted

In [77]:
train_col = X_train.columns

In [78]:
file = 'train_col.txt'
with open(file, 'w') as filetowrite:
    for i in train_col:
        filetowrite.write(str(i) + '\n')

In [147]:
with open('train_col.txt', 'r') as filehandle:
    train_col = filehandle.readlines()

# Strip newline characters from each line
train_col = [line.strip() for line in train_col]
train_col

['BLUE TOP LEVEL',
 'BLUE JUNGLE LEVEL',
 'BLUE SUPPORT LEVEL',
 'BLUE ADC LEVEL',
 'BLUE MID LEVEL',
 'RED TOP LEVEL',
 'RED JUNGLE LEVEL',
 'RED MID LEVEL',
 'RED ADC LEVEL',
 'RED SUPPORT LEVEL',
 'RED TOP INHIB',
 'RED MID INHIB',
 'RED_BOT_INHIB',
 'BLUE TOP INHIB',
 'BLUE MID INHIB',
 'BLUE_BOT_INHIB',
 'RED FIRE DRAGON',
 'RED AIR DRAGON',
 'RED EARTH DRAGON',
 'RED WATER DRAGON',
 'RED HEXTECH DRAGON',
 'RED CHEMTECH DRAGON',
 'RED ELDER DRAGON',
 'BLUE FIRE DRAGON',
 'BLUE AIR DRAGON',
 'BLUE EARTH DRAGON',
 'BLUE WATER DRAGON',
 'BLUE HEXTECH DRAGON',
 'BLUE CHEMTECH DRAGON',
 'BLUE ELDER DRAGON',
 'RED BARON',
 'BLUE BARON',
 'RED GRUBS',
 'BLUE GRUBS',
 'BLUE TOP KDA',
 'BLUE JUNGLE KDA',
 'BLUE UTILITY KDA',
 'BLUE BOTTOM KDA',
 'BLUE MIDDLE KDA',
 'RED TOP KDA',
 'RED JUNGLE KDA',
 'RED MIDDLE KDA',
 'RED BOTTOM KDA',
 'RED UTILITY KDA',
 'BLUE TOP CS/MIN',
 'BLUE JUNGLE CS/MIN',
 'BLUE MID CS/MIN',
 'BLUE ADC CS/MIN',
 'RED TOP CS/MIN',
 'RED JUNGLE CS/MIN',
 'RED MID CS/MIN',
 'RED ADC CS/MIN',
 'RED TOP_LANE OUTER_TURRET',
 'RED TOP_LANE INNER_TURRET',
 'RED TOP_LANE BASE_TURRET',
 'RED MID_LANE OUTER_TURRET',
 'RED MID_LANE INNER_TURRET',
 'RED MID_LANE BASE_TURRET',
 'RED BOT_LANE OUTER_TURRET',
 'RED BOT_LANE INNER_TURRET',
 'RED BOT_LANE BASE_TURRET',
 'BLUE TOP_LANE OUTER_TURRET',
 'BLUE TOP_LANE INNER_TURRET',
 'BLUE TOP_LANE BASE_TURRET',
 'BLUE MID_LANE OUTER_TURRET',
 'BLUE MID_LANE INNER_TURRET',
 'BLUE MID_LANE BASE_TURRET',
 'BLUE BOT_LANE OUTER_TURRET',
 'BLUE BOT_LANE INNER_TURRET',
 'BLUE BOT_LANE BASE_TURRET']

In [139]:
features.columns

Index(['BLUE TOP LEVEL', 'BLUE JUNGLE LEVEL', 'BLUE SUPPORT LEVEL',
       'BLUE ADC LEVEL', 'BLUE MID LEVEL', 'RED TOP LEVEL', 'RED JUNGLE LEVEL',
       'RED MID LEVEL', 'RED ADC LEVEL', 'RED SUPPORT LEVEL', 'RED TOP INHIB',
       'RED MID INHIB', 'RED_BOT_INHIB', 'BLUE TOP INHIB', 'BLUE MID INHIB',
       'BLUE_BOT_INHIB', 'RED FIRE DRAGON', 'RED AIR DRAGON',
       'RED EARTH DRAGON', 'RED WATER DRAGON', 'RED HEXTECH DRAGON',
       'RED CHEMTECH DRAGON', 'RED ELDER DRAGON', 'BLUE FIRE DRAGON',
       'BLUE AIR DRAGON', 'BLUE EARTH DRAGON', 'BLUE WATER DRAGON',
       'BLUE HEXTECH DRAGON', 'BLUE CHEMTECH DRAGON', 'BLUE ELDER DRAGON',
       'RED BARON', 'BLUE BARON', 'RED GRUBS', 'BLUE GRUBS', 'BLUE TOP KDA',
       'BLUE JUNGLE KDA', 'BLUE UTILITY KDA', 'BLUE BOTTOM KDA',
       'BLUE MIDDLE KDA', 'RED TOP KDA', 'RED JUNGLE KDA', 'RED MIDDLE KDA',
       'RED BOTTOM KDA', 'RED UTILITY KDA', 'BLUE TOP CS/MIN',
       'BLUE JUNGLE CS/MIN', 'BLUE MID CS/MIN', 'BLUE ADC CS/MIN',
       'RED TOP CS/MIN', 'RED JUNGLE CS/MIN', 'RED MID CS/MIN',
       'RED ADC CS/MIN', 'RED TOP_LANE OUTER_TURRET',
       'RED TOP_LANE INNER_TURRET', 'RED TOP_LANE BASE_TURRET',
       'RED MID_LANE OUTER_TURRET', 'RED MID_LANE INNER_TURRET',
       'RED MID_LANE BASE_TURRET', 'RED BOT_LANE OUTER_TURRET',
       'RED BOT_LANE INNER_TURRET', 'RED BOT_LANE BASE_TURRET',
       'BLUE TOP_LANE OUTER_TURRET', 'BLUE TOP_LANE INNER_TURRET',
       'BLUE TOP_LANE BASE_TURRET', 'BLUE MID_LANE OUTER_TURRET',
       'BLUE MID_LANE INNER_TURRET', 'BLUE MID_LANE BASE_TURRET',
       'BLUE BOT_LANE OUTER_TURRET', 'BLUE BOT_LANE INNER_TURRET',
       'BLUE BOT_LANE BASE_TURRET'],
      dtype='object')

In [140]:
test_encoded = test_encoded_features.reindex(columns=train_col, fill_value=0)

In [141]:
test_encoded

,BLUE TOP LEVEL,BLUE JUNGLE LEVEL,BLUE SUPPORT LEVEL,BLUE ADC LEVEL,BLUE MID LEVEL,RED TOP LEVEL,RED JUNGLE LEVEL,RED MID LEVEL,RED ADC LEVEL,RED SUPPORT LEVEL,...,RED BOT_LANE BASE_TURRET,BLUE TOP_LANE OUTER_TURRET,BLUE TOP_LANE INNER_TURRET,BLUE TOP_LANE BASE_TURRET,BLUE MID_LANE OUTER_TURRET,BLUE MID_LANE INNER_TURRET,BLUE MID_LANE BASE_TURRET,BLUE BOT_LANE OUTER_TURRET,BLUE BOT_LANE INNER_TURRET,BLUE BOT_LANE BASE_TURRET
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [274]:
pred = model.predict(test_encoded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

In [276]:
pred

array([[0.9789699]], dtype=float32)